### ISSUE TITLE
Unable to destroy

### ISSUE THREAD

**Issue by axeltrip** [mendix/DropdownDivConverter#21] opened 2018-10-31 14:00 UTC
Since MX 7.18 the widget gives the following error:
Unable to destroy:: Error while uninitialize NotFoundError: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

The error only occurs when there's an object in the container. If the container is empty the error does not occur.

**Comment by GielvanaltenaFF** [comment] 2019-01-02 15:04
Same problem happened to me in MX 7.21. The widget gives the error "Failed to execute 'removeChild' on Node when closing the page.

Please fix this.

**Comment by GielvanaltenaFF** [comment] 2019-01-02 15:04
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at lo (http://localhost:8081/mxclientsystem/mxui/mxui.js?636820417488889180:52:65296)
    at ha (http://localhost:8081/mxclientsystem/mxui/mxui.js?636820417488889180:52:81991)
    at da (http://localhost:8081/mxclientsystem/mxui/mxui.js?636820417488889180:52:79236)
    at la (http://localhost:8081/mxclientsystem/mxui/mxui.js?636820417488889180:52:78852)
    at Do (http://localhost:8081/mxclientsystem/mxui/mxui.js?636820417488889180:52:77364)
    at ba (http://localhost:8081/mxclientsystem/mxui/mxui.js?636820417488889180:52:85810)
    at ya (http://localhost:8081/mxclientsystem/mxui/mxui.js?636820417488889180:52:85864)
    at ja.render (http://localhost:8081/mxclientsystem/mxui/mxui.js?636820417488889180:52:89683)
    at Oa (http://localhost:8081/mxclientsystem/mxui/mxui.js?636820417488889180:52:87097)
    at http://localhost:8081/mxclientsystem/mxui/mxui.js?636820417488889180:52:90906

**Comment by JelteMX** [comment] 2019-01-09 14:15
As this is an implementation issue and not a bug in the widget, I am now referring to the [troubleshooting](https://github.com/mendix/DropdownDivConverter#troubleshooting) section that explains why this error occurs and how you can fix it.

**Closed by JelteMX** 2019-01-09 14:15 UTC
